import type { Metadata } from "next";
import {
  Luckiest_Guy,
  Fredoka,
  Bebas_Neue,
  Anton,
  League_Gothic,
  Cormorant_Garamond,
} from "next/font/google";
import "./globals.css";

const luckiest = Luckiest_Guy({
  weight: "400",
  subsets: ["latin-ext"],
  variable: "--font-luckiest",
});
const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});
const league = League_Gothic({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-league",
});
const cormorant = Cormorant_Garamond({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cormorant",
});
const fredoka = Fredoka({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-fredoka",
});

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${luckiest.variable} ${fredoka.variable} ${bebas.variable} ${anton.variable} ${league.variable} ${cormorant.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
